# Generated by Django 6.0.5 on 2026-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_image2_room_image3_room_image4_room_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in_time',
            field=models.CharField(default='03:30 PM', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out_time',
            field=models.CharField(default='02:30 PM', max_length=20),
        ),
    ]
