# Generated by Django 6.0.5 on 2026-05-19 03:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_otpverification_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
