# Generated by Django 6.0.5 on 2026-06-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_is_entire_resort_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_entire_resort',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
