# Generated by Django 6.0.5 on 2026-06-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_booking_is_entire_resort_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
