# Generated by Django 6.0.5 on 2026-06-28 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_entire_resort',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.room'),
        ),
    ]
