# Generated by Django 6.0.5 on 2026-06-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_is_entire_resort_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_entire_resort',
        ),
    ]
