# Generated by Django 6.0.5 on 2026-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_is_entire_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
