# Generated by Django 6.0.5 on 2026-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_blockeddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_count',
            new_name='adults',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='adult_capacity',
        ),
        migrations.AddField(
            model_name='booking',
            name='kids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='child_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
